version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions" # Also update Github actions
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: "weekly"

# Check if we're using the latest docker images
- package-ecosystem: "docker"
  directory: "/container"
  schedule:
    interval: "weekly"
